### ISSUE TITLE
Provide README.md

### ISSUE THREAD

**Issue by codemonkey800** [chrpham/cs160#1]
Aside from the file structure of the repo itself, the `README.md` is the first thing user see when they open up a new repo. With that said, I believe it's paramount that a `README.md` file is created to give developers a high overview of what your project accomplishes.

In addition, you should include any necessary build instructions, dependency listings, contribution guide, coding style guide, and an open source license.

![end my suffering](https://i.ytimg.com/vi/nO5ssjxrhb4/maxresdefault.jpg)

**Comment by chrpham** [comment]
can u not jer

**Comment by codemonkey800** [comment]
I find this response extremely troubling but I understand as project maintainer you have a right to pick the direction of the project.

![i have crippling depression](https://i.ytimg.com/vi/zNZayosPy9w/hqdefault.jpg)
